// <auto-generated />
using System;
using Asp_project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asp_project.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210908101917_atualizando")]
    partial class atualizando
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Asp_project.Models.Endereco", b =>
                {
                    b.Property<int>("id_endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Lid_loja")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uid_usuario")
                        .HasColumnType("int");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_endereco");

                    b.HasIndex("Lid_loja")
                        .IsUnique()
                        .HasFilter("[Lid_loja] IS NOT NULL");

                    b.HasIndex("Uid_usuario")
                        .IsUnique();

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Asp_project.Models.Loja", b =>
                {
                    b.Property<int>("id_loja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Uid_usuario")
                        .HasColumnType("int");

                    b.Property<string>("celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descicao_funcionamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dias_e_horas_de_funcionamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_loja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_loja");

                    b.HasIndex("Uid_usuario")
                        .IsUnique();

                    b.ToTable("Loja");
                });

            modelBuilder.Entity("Asp_project.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_usuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Asp_project.Models.Endereco", b =>
                {
                    b.HasOne("Asp_project.Models.Loja", "L")
                        .WithOne("Endereco")
                        .HasForeignKey("Asp_project.Models.Endereco", "Lid_loja");

                    b.HasOne("Asp_project.Models.Usuario", "U")
                        .WithOne("Endereco")
                        .HasForeignKey("Asp_project.Models.Endereco", "Uid_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    //b.Navigation("L");

                    //b.Navigation("U");
                });

            modelBuilder.Entity("Asp_project.Models.Loja", b =>
                {
                    b.HasOne("Asp_project.Models.Usuario", "U")
                        .WithOne("Loja")
                        .HasForeignKey("Asp_project.Models.Loja", "Uid_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    //b.Navigation("U");
                });

            modelBuilder.Entity("Asp_project.Models.Loja", b =>
                {
                    //b.Navigation("Endereco");
                });

            modelBuilder.Entity("Asp_project.Models.Usuario", b =>
                {
                    //b.Navigation("Endereco");

                    //b.Navigation("Loja");
                });
#pragma warning restore 612, 618
        }
    }
}
